os: linux
dist: bionic
language: php
php: 7.4

cache:
  directories:
    - $HOME/.composer/cache

stages:
  - Composer validation
  - Static analyse
  - Coding standards

install:
  - composer self-update
  - composer install --prefer-dist --no-interaction

jobs:
  include:
    - stage: Composer validation
      script: composer validate --no-check-all --strict

    - stage: Unit tests
      script: vendor/bin/phpunit -c phpunit.xml

    - stage: Static analysis
      script: vendor/bin/phpstan analyse -c phpstan.neon

    - stage: Coding standards
      script: vendor/bin/ecs check -c ecs.php

notifications:
  slack: codea-eu:7l0xhGhVfV5viFmSeyaHA6Pl

