os: linux
dist: bionic
language: php
php: 7.4

cache:
  directories:
    - $HOME/.composer/cache

stages:
  - Composer validation
  - Static analyse
  - Coding standards

install:
  - composer self-update
  - composer install --prefer-dist --no-interaction

jobs:
  include:
    - stage: Composer validation
      script: composer validate --no-check-all --strict

    - stage: Static analyse
      script: vendor/bin/phpstan analyse src -l max -c phpstan.neon

    - stage: Coding standards
      script: vendor/bin/ecs check src --config ecs.php

notifications:
  email:
    on_success: never
