name: Composer validation
on:
  push:
    branches:
      - master

jobs:
  composer:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '8.0' ]

    name: PHP ${{ matrix.php }} - Composer validation
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - run: composer validate --no-check-all --strict
