name: Tests
on:
  push:
    branches:
      - master

jobs:
  composer:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        php: [ '8.0' ]

    name: PHP ${{ matrix.php }} - Composer validation
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - run: composer validate --no-check-all --strict

  phpunit:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        php: [ '8.0' ]

    name: PHP ${{ matrix.php }} - Unit Tests
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - run: composer install --no-progress
      - run: vendor/bin/phpunit -c phpunit.xml

  phpstan:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        php: [ '8.0' ]

    name: PHP ${{ matrix.php }} - Static Analyse
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - run: composer install --no-progress
      - run: vendor/bin/phpstan analyse -c phpstan.neon

  ecs:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        php: [ '8.0' ]

    name: PHP ${{ matrix.php }} - Coding Standards
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - run: composer install --no-progress
      - run: vendor/bin/ecs check -c ecs.php
