name: Tests

on:
  push:
    branches:
      - master

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.0']

    name: PHP ${{ matrix.php }} tests
    steps:
        -   uses: actions/checkout@v2
        -   uses: shivammathur/setup-php@v1
            with:
                php-version: ${{ matrix.php }}
                coverage: none

        -   run: composer install --no-progress
        -   run: vendor/bin/phpunit -c phpunit.xml
    
  static-analyse:    
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.0']

    name: PHP ${{ matrix.php }} tests
    steps:
        -   uses: actions/checkout@v2
        -   uses: shivammathur/setup-php@v1
            with:
                php-version: ${{ matrix.php }}
                coverage: none

        -   run: composer install --no-progress
        -   run: vendor/bin/phpstan analyse -c phpstan.neon
